### ISSUE TITLE
Disabled ffmpeg-wasm node when running under docker

### ISSUE THREAD

**Issue by thejollypop** [bartbutenaers/node-red-contrib-ffmpeg-wasm#1]
Hi Bart, 
First of all great work! I admire your enthusiasm :)
Lately I found [ffmpeg.wasm](https://ffmpegwasm.github.io/#demo) to be my last resort if running NR under DOCKER.
Unfortunately when I tried the [official Node-Red docker architecture](https://nodered.org/docs/getting-started/docker) (LINUX) I got it with Node.js v10.23.1.
So I ran the proposed npm command:
`npm install bartbutenaers/node-red-contrib-ffmpeg-wasm --experimental-worker`
and even yarn:
`yarn add bartbutenaers/node-red-contrib-ffmpeg-wasm --experimental-worker`
but now luck. Here's what I get:

![image](https://user-images.githubusercontent.com/75426675/106052631-7539b380-60f2-11eb-9e9b-3acb69dd5854.png)

Is this a bug? Should I try force upgrade of the docker to node.js V12? (no luck here too...) 
Thanks! Gil

**Comment by bartbutenaers** [comment]
Hey Gil,

Thanks for the feedback!

> the official Node-Red docker architecture (LINUX) I got it with Node.js v10.23.1.

There are a number of different [image variations](https://github.com//node-red/node-red-docker#image-variations) available for the Node-RED docker image.  In that link you can find a table, where you can see how you can get a docker image for Node-RED based on NodeJs 12.

If I were you, I would try to use NodeJs version 12!  The experimental implementation of wasm in NodeJs 10 will most certainly give you a lot of headaches!

P.S. Keep in mind that this repository is not actively maintained!

Good luck with it!!
Bart

**Comment by thejollypop** [comment]
Hi Bart,
Thanks for the prompt response:)

The docker image (Node.js V12):
`docker run -it -p 1880:1880 -v node_red_data:/data --name mynodered  nodered/node-red:1.2.7-12-amd64`

**Solved** the problem. Thanks a lot!
Gil
